schemadotorg_subtype.settings:
  type: config_entity
  label: Schema.org Subtype settings
  mapping:
    default_field_suffix:
      type: string
      label: 'Default subtype field suffix'
    default_field_label:
      type: label
      label: 'Default subtype field label'
    default_field_description:
      type: label
      label: 'Default subtype field description'
    default_subtypes:
      type: sequence
      label: 'Schema.org default subtype types'
      sequence:
        type: string
        label: 'Schema.org default subtype type'
    default_allowed_values:
      type: sequence
      label: 'Schema.org default subtypes allowed values'
      sequence:
        type: sequence
        label: 'Schema.org default subtype allowed values'
        sequence:
          type: string
          label: 'Schema.org default subtype allowed value'
