<?php

/**
 * @file
 * Provides a class registration submission entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\class_registration_submission\Entity\ClassRegistrationSubmission;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function class_registration_submission_theme() {
  return [
    'class_registration_submission' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for class registration submission templates.
 *
 * Default template: class-registration-submission.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the class registration submission information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_class_registration_submission(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function class_registration_submission_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish class registration submissions.
      $storage = \Drupal::entityTypeManager()->getStorage('class_registration_submission');
      $class_registration_submission_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($class_registration_submission_ids) as $class_registration_submission) {
        $class_registration_submission->set('status', FALSE);
        $class_registration_submission->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize class registration submissions.
      $storage = \Drupal::entityTypeManager()->getStorage('class_registration_submission');
      $class_registration_submission_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($class_registration_submission_ids) as $class_registration_submission) {
        $class_registration_submission->setOwnerId(0);
        $class_registration_submission->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function class_registration_submission_user_predelete(UserInterface $account) {
  // Delete class registration submissions.
  $storage = \Drupal::entityTypeManager()->getStorage('class_registration_submission');
  $class_registration_submission_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $class_registration_submissions = $storage->loadMultiple($class_registration_submission_ids);
  $storage->delete($class_registration_submissions);
}
