<?php

/**
 * @file
 * Primary module hooks for JSON:API Event Dispatcher module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Access\AccessResultInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\jsonapi_event_dispatcher\Event\JsonApiEntityFieldFilterAccessEvent;
use Drupal\jsonapi_event_dispatcher\Event\JsonApiEntityFilterAccessEvent;

/**
 * Implements hook_jsonapi_entity_filter_access().
 */
function jsonapi_event_dispatcher_jsonapi_entity_filter_access(EntityTypeInterface $entityType, AccountInterface $account): array {
  /** @var \Drupal\hook_event_dispatcher\Manager\HookEventDispatcherManagerInterface $manager */
  $manager = Drupal::service('hook_event_dispatcher.manager.legacy');
  $event = new JsonApiEntityFilterAccessEvent($entityType, $account);
  $manager->register($event);

  return $event->getAccessResults();
}

/**
 * Implements hook_jsonapi_entity_field_filter_access().
 */
function jsonapi_event_dispatcher_jsonapi_entity_field_filter_access(FieldDefinitionInterface $fieldDefinition, AccountInterface $account): AccessResultInterface {
  /** @var \Drupal\hook_event_dispatcher\Manager\HookEventDispatcherManagerInterface $manager */
  $manager = Drupal::service('hook_event_dispatcher.manager.legacy');
  $event = new JsonApiEntityFieldFilterAccessEvent($fieldDefinition, $account);
  $manager->register($event);

  return $event->getAccessResult();
}
