<?php

/**
 * @file
 * Allows an Office hours field to be used to create OpeningHoursSpecification.
 */

declare(strict_types = 1);

use Drupal\Core\Field\FieldItemInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Implements hook_schemadotorg_property_field_alter().
 */
function schemadotorg_office_hours_schemadotorg_property_field_alter(
  string $schema_type,
  string $schema_property,
  array &$field_storage_values,
  array &$field_values,
  ?string &$widget_id,
  array &$widget_settings,
  ?string &$formatter_id,
  array &$formatter_settings
): void {
  // Make sure the field type is set to 'office_hours'.
  if ($field_storage_values['type'] !== 'office_hours') {
    return;
  }

  // Office hours must be unlimited.
  $field_storage_values['cardinality'] = FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED;
  // Set default settings.
  $field_storage_values['settings'] = [
    'time_format' => 'G',
    'element_type' => 'office_hours_datelist',
    'increment' => 30,
    'required_start' => FALSE,
    'limit_start' => '',
    'required_end' => FALSE,
    'limit_end' => '',
    'comment' => 1,
    'valhrs' => FALSE,
    'cardinality_per_day' => 2,
  ];
}

/**
 * Implements hook_schemadotorg_jsonld_schema_property_alter().
 */
function schemadotorg_office_hours_schemadotorg_jsonld_schema_property_alter(mixed &$value, FieldItemInterface $item): void {
  $field_type = $item->getFieldDefinition()->getType();
  if ($field_type !== 'office_hours') {
    return;
  }

  $schema_days = [
    'https://schema.org/Sunday',
    'https://schema.org/Monday',
    'https://schema.org/Tuesday',
    'https://schema.org/Wednesday',
    'https://schema.org/Thursday',
    'https://schema.org/Friday',
    'https://schema.org/Saturday',
  ];

  $value = ['@type' => 'OpeningHoursSpecification'];
  if (isset($schema_days[$item->day])) {
    $value['dayOfWeek'] = $schema_days[$item->day];
  }
  if ($item->starthours) {
    $value['opens'] = preg_replace('/(\d\d)$/', ':$1', (string) $item->starthours);
  }
  if ($item->endhours) {
    $value['closes'] = preg_replace('/(\d\d)$/', ':$1', (string) $item->endhours);
  }
  if ($item->comment) {
    $value['description'] = $item->comment;
  }
}
