<?php

/**
 * @file
 * Provides a volunteer time record entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;
use Drupal\volunteer_time_record\Entity\VolunteerTimeRecord;

/**
 * Implements hook_theme().
 */
function volunteer_time_record_theme() {
  return [
    'volunteer_time_record' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for volunteer time record templates.
 *
 * Default template: volunteer-time-record.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the volunteer time record information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_volunteer_time_record(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function volunteer_time_record_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish volunteer time records.
      $storage = \Drupal::entityTypeManager()->getStorage('volunteer_time_record');
      $volunteer_time_record_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($volunteer_time_record_ids) as $volunteer_time_record) {
        $volunteer_time_record->set('status', FALSE);
        $volunteer_time_record->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize volunteer time records.
      $storage = \Drupal::entityTypeManager()->getStorage('volunteer_time_record');
      $volunteer_time_record_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($volunteer_time_record_ids) as $volunteer_time_record) {
        $volunteer_time_record->setOwnerId(0);
        $volunteer_time_record->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function volunteer_time_record_user_predelete(UserInterface $account) {
  // Delete volunteer time records.
  $storage = \Drupal::entityTypeManager()->getStorage('volunteer_time_record');
  $volunteer_time_record_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $volunteer_time_records = $storage->loadMultiple($volunteer_time_record_ids);
  $storage->delete($volunteer_time_records);
  // Delete old revisions.
  $volunteer_time_record_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->execute();
  foreach (array_keys($volunteer_time_record_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
