<?php

/**
 * @file
 * Provides a class session entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\class_session\Entity\ClassSession;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function class_session_theme() {
  return [
    'class_session' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for class session templates.
 *
 * Default template: class-session.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the class session information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_class_session(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function class_session_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish class sessions.
      $storage = \Drupal::entityTypeManager()->getStorage('class_session');
      $class_session_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($class_session_ids) as $class_session) {
        $class_session->set('status', FALSE);
        $class_session->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize class sessions.
      $storage = \Drupal::entityTypeManager()->getStorage('class_session');
      $class_session_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($class_session_ids) as $class_session) {
        $class_session->setOwnerId(0);
        $class_session->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function class_session_user_predelete(UserInterface $account) {
  // Delete class sessions.
  $storage = \Drupal::entityTypeManager()->getStorage('class_session');
  $class_session_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $class_sessions = $storage->loadMultiple($class_session_ids);
  $storage->delete($class_sessions);
}
