schemadotorg_content_moderation.settings:
  type: config_entity
  label: Schema.org Content Moderation settings
  mapping:
    default_workflows:
      type: sequence
      label: 'Default workflows'
      sequence:
        type: string
        label: 'Default workflow'
