<?php

/**
 * @file
 * Assists with creating and mapping taxonomy vocabularies and terms.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\FieldItemInterface;
use Drupal\Core\Field\Plugin\Field\FieldType\EntityReferenceItem;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\schemadotorg\Element\SchemaDotOrgSettings;
use Drupal\schemadotorg\SchemaDotOrgMappingInterface;

/**
 * Implements hook_help().
 */
function schemadotorg_taxonomy_help(string $route_name, RouteMatchInterface $route_match): string|array|null {
  /** @var \Drupal\schemadotorg\SchemaDotOrgHelpManagerInterface $help_manager */
  $help_manager = \Drupal::service('schemadotorg.help_manager');
  return $help_manager->buildHelpPage($route_name, $route_match);
}

/* ************************************************************************** */
// Schema.org JSON-LD alterations.
/* ************************************************************************** */

/**
 * Implements hook_schemadotorg_jsonld_schema_property_alter().
 */
function schemadotorg_taxonomy_schemadotorg_jsonld_schema_property_alter(mixed &$value, FieldItemInterface $item): void {
  // If the JSON-LD item value is null for an entity_reference:taxonomy_terms,
  // the term's name is used as the JSON-LD item value.
  if (is_null($value)
    && $item instanceof EntityReferenceItem
    && $item->getDataDefinition()->getSetting('target_type') === 'taxonomy_term'
    && $item->entity) {
    $value = $item->entity->label();
  }
}

/**
 * Implements hook_schemadotorg_jsonld_schema_type_entity_load().
 */
function schemadotorg_taxonomy_schemadotorg_jsonld_schema_type_entity_load(array &$data, EntityInterface $entity): void {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyJsonLdManager $taxonomy_jsonld_manager */
  $taxonomy_jsonld_manager = \Drupal::service('schemadotorg_taxonomy.jsonld_manager');
  $taxonomy_jsonld_manager->load($data, $entity);
}

/**
 * Implements hook_schemadotorg_jsonld_schema_type_entity_alter().
 */
function schemadotorg_taxonomy_schemadotorg_jsonld_schema_type_entity_alter(array &$data, EntityInterface $entity): void {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyJsonLdManager $taxonomy_jsonld_manager */
  $taxonomy_jsonld_manager = \Drupal::service('schemadotorg_taxonomy.jsonld_manager');
  $taxonomy_jsonld_manager->alter($data, $entity);
}

/**
 * Implements hook_preprocess_html().
 */
function schemadotorg_taxonomy_preprocess_html(array &$variables): void {
  // Make sure the Schema.org JSON-LD module exists.
  if (!\Drupal::moduleHandler()->moduleExists('schemadotorg_jsonld')) {
    return;
  }

  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyJsonLdManager $taxonomy_jsonld_manager */
  $taxonomy_jsonld_manager = \Drupal::service('schemadotorg_taxonomy.jsonld_manager');
  $taxonomy_jsonld_manager->preprocessHtml($variables);
}

/* ************************************************************************** */
// Default type vocabulary.
/* ************************************************************************** */

/**
 * Implements hook_schemadotorg_mapping_insert().
 */
function schemadotorg_taxonomy_schemadotorg_mapping_insert(SchemaDotOrgMappingInterface $mapping): void {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyDefaultVocabularyManagerInterface $taxonomy_default_vocabulary_manager */
  $taxonomy_default_vocabulary_manager = \Drupal::service('schemadotorg_taxonomy.default_vocabulary_manager');
  $taxonomy_default_vocabulary_manager->mappingInsert($mapping);
}

/* ************************************************************************** */
// Default property vocabulary.
/* ************************************************************************** */

/**
 * Implements hook_schemadotorg_property_field_type_alter().
 */
function schemadotorg_taxonomy_schemadotorg_property_field_type_alter(array &$field_types, string $schema_type, string $schema_property): void {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyPropertyVocabularyManagerInterface $taxonomy_property_vocabulary_manager */
  $taxonomy_property_vocabulary_manager = \Drupal::service('schemadotorg_taxonomy.property_vocabulary_manager');
  $taxonomy_property_vocabulary_manager->propertyFieldTypeAlter($field_types, $schema_type, $schema_property);
}

/**
 * Implements hook_schemadotorg_property_field_alter().
 */
function schemadotorg_taxonomy_schemadotorg_property_field_alter(
  string $schema_type,
  string $schema_property,
  array &$field_storage_values,
  array &$field_values,
  ?string &$widget_id,
  array &$widget_settings,
  ?string &$formatter_id,
  array &$formatter_settings
): void {
  /** @var \Drupal\schemadotorg_taxonomy\SchemaDotOrgTaxonomyPropertyVocabularyManagerInterface $taxonomy_property_vocabulary_manager */
  $taxonomy_property_vocabulary_manager = \Drupal::service('schemadotorg_taxonomy.property_vocabulary_manager');
  $taxonomy_property_vocabulary_manager->propertyFieldAlter(
    $schema_type,
    $schema_property,
    $field_storage_values,
    $field_values,
    $widget_id,
    $widget_settings,
    $formatter_id,
    $formatter_settings
  );
}

/* ************************************************************************** */
// Taxonomy settings form.
/* ************************************************************************** */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function schemadotorg_taxonomy_form_schemadotorg_types_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  $config = \Drupal::configFactory()->getEditable('schemadotorg_taxonomy.settings');

  $form['schemadotorg_taxonomy'] = [
    '#type' => 'details',
    '#title' => t('Taxonomy settings'),
    '#open' => TRUE,
    '#tree' => TRUE,
  ];
  $form['schemadotorg_taxonomy']['default_vocabularies_group_label'] = [
    '#type' => 'textfield',
    '#title' => t('Default vocabularies group label'),
    '#description' => t('Enter the field group label for default vocabularies.'),
    '#default_value' => $config->get('default_vocabularies_group_label'),
    '#required' => TRUE,
    '#access' => \Drupal::moduleHandler()->moduleExists('field_group'),
  ];
  $form['schemadotorg_taxonomy']['default_vocabularies'] = [
    '#type' => 'schemadotorg_settings',
    '#settings_type' => SchemaDotOrgSettings::ASSOCIATIVE_GROUPED,
    '#settings_format' => 'propertyName|id:vocabulary_id,label:Vocabulary name,description: Vocabulary description goes here',
    '#title' => t('Default vocabularies'),
    '#description' => t('Enter default vocabularies that will be added to every Schema.org content type.'),
    '#default_value' => $config->get('default_vocabularies'),
  ];

  // Add submit callback.
  $form['#submit'][] = 'schemadotorg_taxonomy_settings_form_submit';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function schemadotorg_taxonomy_form_schemadotorg_properties_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  $config = \Drupal::configFactory()->getEditable('schemadotorg_taxonomy.settings');

  $form['schemadotorg_taxonomy'] = [
    '#type' => 'details',
    '#title' => t('Taxonomy settings'),
    '#open' => TRUE,
    '#tree' => TRUE,
  ];
  $form['schemadotorg_taxonomy']['property_vocabularies'] = [
    '#type' => 'schemadotorg_settings',
    '#settings_type' => SchemaDotOrgSettings::ASSOCIATIVE_GROUPED,
    '#settings_format' => 'propertyName|id:vocabulary_id,label:Vocabulary name,description:Vocabulary description goes here,auto_create:true',
    '#title' => t('Default vocabulary properties'),
    '#description' => t('Enter Schema.org properties that should be mapped to a vocabulary.')
    . '<br/>'
    . t('If the mapped vocabulary does exist it will be created when the Schema.org property mapping is created.'),
    '#description_link' => 'properties',
    '#default_value' => $config->get('property_vocabularies'),
  ];

  // Add submit callback.
  $form['#submit'][] = 'schemadotorg_taxonomy_settings_form_submit';
}

/**
 * Form submission handler for schemadotorg_properties_settings_form().
 *
 * @see schemadotorg_taxonomy_form_schemadotorg_type_settings_form_alter()
 * @see schemadotorg_taxonomy_form_schemadotorg_properties_settings_form_alter()
 */
function schemadotorg_taxonomy_settings_form_submit(array &$form, FormStateInterface $form_state): void {
  $config = \Drupal::configFactory()->getEditable('schemadotorg_taxonomy.settings');
  $values = $form_state->getValue('schemadotorg_taxonomy');
  foreach ($values as $key => $value) {
    $config->set($key, $value);
  }
  $config->save();
}
