schemadotorg_jsonld_endpoint.settings:
  type: config_entity
  label: Schema.org JSON-LD endpoint settings
  mapping:
    entity_type_endpoints:
      type: sequence
      label: 'Entity type endpoints'
      sequence:
        type: string
        label: 'Entity type endpoint'
