<?php

/**
 * @file
 * Provides a bike church patron waiver entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\adult_patron_waver\Entity\AdultPatronWaver;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function adult_patron_waver_theme() {
  return [
    'adult_patron_waver' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for bike church patron waiver templates.
 *
 * Default template: adult-patron-waver.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the bike church patron waiver information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_adult_patron_waver(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function adult_patron_waver_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish bike church patron waivers.
      $storage = \Drupal::entityTypeManager()->getStorage('adult_patron_waver');
      $adult_patron_waver_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($adult_patron_waver_ids) as $adult_patron_waver) {
        $adult_patron_waver->set('status', FALSE);
        $adult_patron_waver->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize bike church patron waivers.
      $storage = \Drupal::entityTypeManager()->getStorage('adult_patron_waver');
      $adult_patron_waver_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($adult_patron_waver_ids) as $adult_patron_waver) {
        $adult_patron_waver->setOwnerId(0);
        $adult_patron_waver->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function adult_patron_waver_user_predelete(UserInterface $account) {
  // Delete bike church patron waivers.
  $storage = \Drupal::entityTypeManager()->getStorage('adult_patron_waver');
  $adult_patron_waver_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $adult_patron_wavers = $storage->loadMultiple($adult_patron_waver_ids);
  $storage->delete($adult_patron_wavers);
}
