_core:
  default_config_hash: DiMIF3-JzC2TzjWkH4h5zlZ17OaIitsuaq1UGb-KvPw
favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'private://favicon_0.ico'
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'private://nbw_logo_32_0.png'
  use_default: false
cdn_provider: custom
cdn_custom_img: 'https://cdn.jsdelivr.net/npm/@uswds/uswds@3.3.0/dist/img'
cdn_custom_css: 'https://cdn.jsdelivr.net/npm/@uswds/uswds@3.3.0/dist/css/uswds.css'
cdn_custom_css_min: 'https://cdn.jsdelivr.net/npm/@uswds/uswds@3.3.0/dist/css/uswds.min.css'
cdn_custom_js: 'https://cdn.jsdelivr.net/npm/@uswds/uswds@3.3.0/dist/js/uswds.js'
cdn_custom_js_min: 'https://cdn.jsdelivr.net/npm/@uswds/uswds@3.3.0/dist/js/uswds.min.js'
uswds_header_style: extended
uswds_header_mega: 0
uswds_header_mega_display_second: 0
uswds_government_banner: 0
uswds_footer_style: big
uswds_footer_agency: 1
uswds_footer_agency_name: NBW
uswds_footer_agency_url: '#agency'
uswds_footer_agency_logo: nbw_logo.png
uswds_contact_center: 'NBW Contacts:'
uswds_email: info@nbwdata.com
uswds_phone: '(800) CALL-NBW'
uswds_facebook: '#facebook'
uswds_instagram: '#instagram'
uswds_linkedin: '#linkedin'
uswds_twitter: '#twitter'
uswds_youtube: '#youtube'
uswds_rss: /rss.xml
uswds_paragraphs_edge_to_edge: 0
uswds_menu_accordion_duplicate_parent: 0
uswds_menu_bypass:
  primary_menu: 0
  secondary_menu: 0
  sidebar_first: 0
  sidebar_second: 0
  footer_menu: 0
