# Schema for the views plugins of the Download Statistics module.

views.field.download_statistics_numeric:
  type: views.field.numeric
  label: 'Numeric values from the Download Statistics module'

views.field.download_statistics_timestamp:
  type: views.field.date
  label: 'The most recent time the file has been downloaded'
