<?php

/**
 * @file
 * Provides a class attendance record entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\class_attendance_record\Entity\ClassAttendanceRecord;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function class_attendance_record_theme() {
  return [
    'class_attendance_record' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for class attendance record templates.
 *
 * Default template: class-attendance-record.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the class attendance record information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_class_attendance_record(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function class_attendance_record_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_reassign':
      // Anonymize class attendance records.
      $storage = \Drupal::entityTypeManager()->getStorage('class_attendance_record');
      $class_attendance_record_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($class_attendance_record_ids) as $class_attendance_record) {
        $class_attendance_record->setOwnerId(0);
        $class_attendance_record->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function class_attendance_record_user_predelete(UserInterface $account) {
  // Delete class attendance records.
  $storage = \Drupal::entityTypeManager()->getStorage('class_attendance_record');
  $class_attendance_record_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $class_attendance_records = $storage->loadMultiple($class_attendance_record_ids);
  $storage->delete($class_attendance_records);
}
