<?php

/**
 * @file
 * Integrates the Paragraphs with the Schema.org Blueprints module.
 */

declare(strict_types = 1);

use Drupal\Component\Utility\Unicode;
use Drupal\Core\Field\FieldItemInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity\File;
use Drupal\paragraphs\ParagraphInterface;
use Drupal\paragraphs\ParagraphsTypeInterface;
use Drupal\schemadotorg\Element\SchemaDotOrgSettings;
use Drupal\schemadotorg\SchemaDotOrgMappingInterface;

/**
 * Implements hook_help().
 */
function schemadotorg_paragraphs_help(string $route_name, RouteMatchInterface $route_match): string|array|null {
  /** @var \Drupal\schemadotorg\SchemaDotOrgHelpManagerInterface $help_manager */
  $help_manager = \Drupal::service('schemadotorg.help_manager');
  return $help_manager->buildHelpPage($route_name, $route_match);
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function schemadotorg_paragraphs_paragraphs_type_presave(ParagraphsTypeInterface $paragraphs_type): void {
  if ($paragraphs_type->getIconFile()) {
    return;
  }

  /** @var \Drupal\Core\Extension\ModuleExtensionList $module_extension_list */
  $module_extension_list = \Drupal::service('extension.list.module');

  /** @var \Drupal\Core\File\FileSystemInterface $file_system */
  $file_system = \Drupal::service('file_system');

  // Get installed module names with the 'schemadotorg_paragraphs' module last.
  $module_names = array_keys(\Drupal::moduleHandler()->getModuleList());
  $module_names = array_combine($module_names, $module_names);
  unset($module_names['schemadotorg_paragraphs']);
  $module_names['schemadotorg_paragraphs'] = 'schemadotorg_paragraphs';

  foreach ($module_names as $module_name) {
    $icon_path = $module_extension_list->getPath($module_name) . '/images/schemadotorg_paragraphs/' . $paragraphs_type->id() . '.svg';
    if (file_exists($icon_path)) {
      $icon_directory = 'public://paragraphs_type_icon';
      $file_system->prepareDirectory($icon_directory, $file_system::CREATE_DIRECTORY || $file_system::MODIFY_PERMISSIONS);

      $file_uri = $file_system->copy($icon_path, $icon_directory . '/' . $file_system->basename($icon_path), $file_system::EXISTS_REPLACE);
      $file_entity = File::create(['uri' => $file_uri]);
      $file_entity->save();
      $paragraphs_type->set('icon_uuid', $file_entity->uuid());
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function schemadotorg_paragraphs_schemadotorg_mapping_presave(SchemaDotOrgMappingInterface $mapping): void {
  if (!$mapping->isNew() || $mapping->getTargetEntityTypeId() !== 'paragraph') {
    return;
  }

  $schema_type = $mapping->getSchemaType();
  if (!_schemadotorg_paragraphs_use_library($schema_type)) {
    return;
  }

  /** @var \Drupal\paragraphs\ParagraphsTypeInterface $paragraph_type */
  $paragraph_type = $mapping->getTargetEntityBundleEntity();
  $paragraph_type->setThirdPartySetting('paragraphs_library', 'allow_library_conversion', TRUE);
  $paragraph_type->save();
}

/**
 * Implements hook_schemadotorg_property_field_alter().
 */
function schemadotorg_paragraphs_schemadotorg_property_field_alter(
  string $schema_type,
  string $schema_property,
  array &$field_storage_values,
  array &$field_values,
  ?string &$widget_id,
  array &$widget_settings,
  ?string &$formatter_id,
  array &$formatter_settings
): void {
  // Check that the field is an entity_reference_revisions type that is
  // targeting paragraphs.
  if ($field_storage_values['type'] !== 'entity_reference_revisions'
    || $field_storage_values['settings']['target_type'] !== 'paragraph') {
    return;
  }

  /** @var \Drupal\schemadotorg\SchemaDotOrgMappingStorage $mapping_storage */
  $mapping_storage = \Drupal::entityTypeManager()->getStorage('schemadotorg_mapping');

  // If any of the target bundles use the Paragraphs library,
  // append 'from_library' to target bundles.
  $target_type = $field_storage_values['settings']['target_type'];
  $handler_settings = $field_values['settings']['handler_settings'] ?? [];

  $target_bundles = $handler_settings['target_bundles'] ?? [];
  foreach ($target_bundles as $target_bundle) {
    /** @var \Drupal\schemadotorg\SchemaDotOrgMappingInterface $target_mapping */
    $target_mappings = $mapping_storage->loadByProperties([
      'target_entity_type_id' => $target_type,
      'target_bundle' => $target_bundle,
    ]);
    if (!$target_mappings) {
      continue;
    }

    /** @var \Drupal\schemadotorg\SchemaDotOrgMappingInterface $target_mapping */
    $target_mapping = reset($target_mappings);
    $target_schema_type = $target_mapping->getSchemaType();
    if (_schemadotorg_paragraphs_use_library($target_schema_type)) {
      $target_bundles['from_library'] = 'from_library';
      break;
    }
  }

  // Set the target bundles drag and drop order.
  $handler_settings['target_bundles_drag_drop'] = [];
  $weight = 0;
  foreach ($target_bundles as $target_bundle) {
    $handler_settings['target_bundles_drag_drop'][$target_bundle] = [
      'weight' => $weight,
      'enabled' => TRUE,
    ];
    $weight++;
  }

  $field_values['settings']['handler_settings'] = $handler_settings;
  $field_values['settings']['handler_settings']['target_bundles'] = $target_bundles;

  // Widget.
  $widget_id = 'paragraphs';

  // Set the default paragraph type to 'none', to provide a cleaner initial UX
  // because all Schema.org fields/properties are optional.
  $widget_settings['default_paragraph_type'] = '_none';
}

/* ************************************************************************** */
// Schema.org JSON-LD alterations.
/* ************************************************************************** */

/**
 * Implements hook_schemadotorg_jsonld_schema_property_alter().
 *
 * Adds paragraph from paragraphs library to JSON-LD.
 */
function schemadotorg_paragraphs_schemadotorg_jsonld_schema_property_alter(mixed &$value, FieldItemInterface $item): void {
  // Make sure the Paragraphs Library module is enabled.
  if (!\Drupal::moduleHandler()->moduleExists('paragraphs_library')) {
    return;
  }

  $field_storage_definition = $item->getFieldDefinition()->getFieldStorageDefinition();
  // Check that the field is an entity_reference_revisions type that is
  // targeting paragraphs.
  if ($field_storage_definition->getType() !== 'entity_reference_revisions'
    || $field_storage_definition->getSetting('target_type') !== 'paragraph') {
    return;
  }

  // Check that the value is NOT NULL.
  if (!is_null($value)) {
    return;
  }

  // Check that the item entity is a paragraph from the
  // Paragraphs library.
  if (empty($item->entity)
    || !$item->entity instanceof ParagraphInterface
    || $item->entity->getType() !== 'from_library') {
    return;
  }

  /** @var \Drupal\paragraphs\ParagraphInterface $from_library_paragraph */
  $from_library_paragraph = $item->entity;
  if (!$from_library_paragraph->hasField('field_reusable_paragraph')
    || empty($from_library_paragraph->field_reusable_paragraph->entity)) {
    return;
  }

  /** @var \Drupal\paragraphs_library\LibraryItemInterface $from_library_item */
  $from_library_item = $from_library_paragraph->field_reusable_paragraph->entity;
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $from_library_item->paragraphs->entity;
  if (!$from_library_item->hasField('paragraphs')
    || empty($from_library_item->paragraphs->entity)) {
    return;
  }

  /** @var \Drupal\schemadotorg_jsonld\SchemaDotOrgJsonLdBuilderInterface $jsonld_builder */
  $jsonld_builder = \Drupal::service('schemadotorg_jsonld.builder');

  // Build the paragraphs JSON-LD.
  $value = $jsonld_builder->buildEntity($paragraph, ['identifier' => FALSE]);
}

/* ************************************************************************** */
// Entity embed for paragraphs library items.
/* ************************************************************************** */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Converts the broken entity embed paragraphs widget into a working select menu
 * that displays paragraphs that have been promoted to the Paragraphs library.
 *
 * @see https://localhost/admin/content/paragraphs
 * @see https://localhost/entity-embed/dialog/basic_html/paragraphs_library
 */
function schemadotorg_paragraphs_form_entity_embed_dialog_alter(array &$form, FormStateInterface $form_state): void {
  // Check that the paragraphs library module is enabled.
  if (!\Drupal::moduleHandler()->moduleExists('paragraphs_library')) {
    return;
  }

  // Check that the embed button is for entity embeds.
  /** @var \Drupal\embed\EmbedButtonInterface $embed_button */
  $embed_button = \Drupal::routeMatch()->getParameter('embed_button');
  if ($embed_button->getTypeId() !== 'entity') {
    return;
  }

  // Check that the entity embed button is for paragraphs.
  $configuration = $embed_button->getTypePlugin()->getConfiguration();
  if ($configuration['entity_type'] !== 'paragraph') {
    return;
  }

  // Alter the 'selected entity' form.
  if (!isset($form['entity_id'])) {
    // Alter the 'Selected entity' markup to use the Paragraph's summary.
    /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
    $paragraph = $form_state->get('entity');
    $summary = $paragraph->getSummaryItems(['show_behavior_summary' => FALSE]);
    $summary = Unicode::truncate(implode(', ', $summary['content']), 120);
    $form['entity']['#markup'] = $paragraph->getParagraphType()->label() . ': ' . $summary;
    return;
  }

  // Collect all the paragraphs ids from paragraphs library items.
  /** @var \Drupal\paragraphs_library\Entity\LibraryItem[] $library_items */
  $library_items = \Drupal::entityTypeManager()
    ->getStorage('paragraphs_library_item')
    ->loadMultiple();
  $paragraph_ids = [];
  foreach ($library_items as $library_item) {
    if ($library_item->paragraphs->target_id) {
      $paragraph_ids[] = $library_item->paragraphs->target_id;
    }
  }

  // Load the paragraphs, filtered by bundle.
  $paragraphs = [];
  if ($paragraph_ids) {
    $query = \Drupal::entityQuery('paragraph');
    $query->condition('id', $paragraph_ids, 'IN');
    if ($configuration['bundles']) {
      $query->condition('type', $configuration['bundles'], 'IN');
    }
    $paragraph_ids = $query->execute();
    if ($paragraph_ids) {
      $paragraphs = \Drupal::entityTypeManager()
        ->getStorage('paragraph')
        ->loadMultiple($paragraph_ids);
    }
  }

  // Build grouped paragraph reference items that display a paragraph's summary.
  // @see \Drupal\paragraphs_library\Entity\LibraryItem::buildLabel
  $options = [];
  /** @var \Drupal\paragraphs\ParagraphInterface[] $paragraphs */
  foreach ($paragraphs as $paragraph) {
    $summary = $paragraph->getSummaryItems(['show_behavior_summary' => FALSE]);
    $summary = Unicode::truncate(implode(', ', $summary['content']), 120);
    $optgroup = $paragraph->getParagraphType()->label();
    $options[$optgroup][$paragraph->id()] = $summary;
  }

  // If there are no paragraph library item, display a message.
  if (empty($options)) {
    $form['entity_id'] = ['#markup' => t('No library items available.')];
    unset($form['actions']);
    return;
  }

  // Sort option groups and options.
  ksort($options);
  foreach ($options as &$optgroup) {
    asort($optgroup);
  }

  // Get the default value.
  if ($form['entity_id']['#default_value'] instanceof ParagraphInterface) {
    $default_value = $form['entity_id']['#default_value']->id();
  }
  else {
    $default_value = $form['entity_id']['#default_value'];
  }

  $form['entity_id'] = [
    '#type' => 'select',
    '#title' => t('Title'),
    '#required' => TRUE,
    '#default_value' => $default_value,
    '#options' => $options,
  ];
}

/* ************************************************************************** */
// Schema.org types settings form.
/* ************************************************************************** */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function schemadotorg_paragraphs_form_schemadotorg_types_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  if (!\Drupal::moduleHandler()->moduleExists('paragraphs_library')) {
    return;
  }

  $config = \Drupal::configFactory()->getEditable('schemadotorg_paragraphs.settings');

  $form['schemadotorg_paragraphs'] = [
    '#type' => 'details',
    '#title' => t('Paragraphs settings'),
    '#open' => TRUE,
    '#tree' => TRUE,
  ];
  $form['schemadotorg_paragraphs']['paragraphs_library'] = [
    '#type' => 'schemadotorg_settings',
    '#settings_type' => SchemaDotOrgSettings::INDEXED,
    '#settings_format' => 'SchemaType',
    '#title' => t('Schema.org types that default to using the Paragraphs library'),
    '#description' => t('Enter Schema.org types that default to using the Paragraphs library.'),
    '#description_link' => 'types',
    '#default_value' => $config->get('paragraphs_library'),
  ];

  // Add submit callback.
  $form['#submit'][] = 'schemadotorg_paragraphs_settings_form_submit';
}

/**
 * Form submission handler for schemadotorg_properties_settings_form.
 *
 * @see schemadotorg_paragraphs_form_schemadotorg_properties_settings_form_alter()
 */
function schemadotorg_paragraphs_settings_form_submit(array &$form, FormStateInterface $form_state): void {
  $config = \Drupal::configFactory()->getEditable('schemadotorg_paragraphs.settings');
  $values = $form_state->getValue('schemadotorg_paragraphs');
  foreach ($values as $key => $value) {
    $config->set($key, $value);
  }
  $config->save();
}

/**
 * Check if a Schema.org type should be added to Paragraphs library.
 *
 * @param string $type
 *   The Schema.org type.
 *
 * @return bool
 *   TRUE if a Schema.org type should be added to Paragraphs library.
 */
function _schemadotorg_paragraphs_use_library(string $type): bool {
  if (!\Drupal::moduleHandler()->moduleExists('paragraphs_library')) {
    return FALSE;
  }

  $paragraphs_library = \Drupal::configFactory()
    ->get('schemadotorg_paragraphs.settings')
    ->get('paragraphs_library');

  /** @var \Drupal\schemadotorg\SchemaDotOrgSchemaTypeManagerInterface $schema_type_manager */
  $schema_type_manager = \Drupal::service('schemadotorg.schema_type_manager');
  return $schema_type_manager->isSubTypeOf($type, $paragraphs_library);
}
