<?php

/**
 * @file
 * Provides a bike parts item entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\bike_part\Entity\BikePartsItem;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function bike_part_theme() {
  return [
    'bike_parts_item' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for bike parts item templates.
 *
 * Default template: bike-parts-item.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the bike parts item information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_bike_parts_item(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function bike_part_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish bike parts items.
      $storage = \Drupal::entityTypeManager()->getStorage('bike_parts_item');
      $bike_parts_item_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($bike_parts_item_ids) as $bike_parts_item) {
        $bike_parts_item->set('status', FALSE);
        $bike_parts_item->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize bike parts items.
      $storage = \Drupal::entityTypeManager()->getStorage('bike_parts_item');
      $bike_parts_item_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($bike_parts_item_ids) as $bike_parts_item) {
        $bike_parts_item->setOwnerId(0);
        $bike_parts_item->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function bike_part_user_predelete(UserInterface $account) {
  // Delete bike parts items.
  $storage = \Drupal::entityTypeManager()->getStorage('bike_parts_item');
  $bike_parts_item_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $bike_parts_items = $storage->loadMultiple($bike_parts_item_ids);
  $storage->delete($bike_parts_items);
  // Delete old revisions.
  $bike_parts_item_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->execute();
  foreach (array_keys($bike_parts_item_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
