administer youth application waiver:
  title: 'Administer youth application waiver settings'
  restrict access: true
delete youth application waiver:
  title: Delete youth application waiver
create youth application waiver:
  title: Create youth application waiver
view youth application waiver:
  title: View youth application waiver
edit youth application waiver:
  title: Edit youth application waiver
