entity.youth_application_waiver.settings:
  title: 'Settings'
  route_name: entity.youth_application_waiver.settings
  base_route: entity.youth_application_waiver.settings
entity.youth_application_waiver.view:
  title: 'View'
  route_name: entity.youth_application_waiver.canonical
  base_route: entity.youth_application_waiver.canonical
entity.youth_application_waiver.edit_form:
  title: 'Edit'
  route_name: entity.youth_application_waiver.edit_form
  base_route: entity.youth_application_waiver.canonical
entity.youth_application_waiver.delete_form:
  title: 'Delete'
  route_name: entity.youth_application_waiver.delete_form
  base_route: entity.youth_application_waiver.canonical
  weight: 10
entity.youth_application_waiver.collection:
  title: 'Youth Application Waivers'
  route_name: entity.youth_application_waiver.collection
  base_route: system.admin_content
  weight: 10
