entity.youth_application_waiver.settings:
  title: 'Youth Application Waiver'
  description: 'Configure a Youth Application Waiver entity type.'
  route_name:  entity.youth_application_waiver.settings
  parent: system.admin_structure
entity.youth_application_waiver.collection:
  title: 'Youth Application Waivers'
  description: 'List of youth application waivers.'
  route_name: entity.youth_application_waiver.collection
  parent: system.admin_content
