<?php
use Drupal\profile\Entity\Profile;
/**
 * @file
 * Primary module hooks for NBW Data App module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function nbw_data_app_preprocess_webform_confirmation(&$vars) {

  $formsToProcess = [
    'bike-church-patron-waiver',
    'nbw_youth_application_waiver',
  ];

  if ($vars['webform']->id() == 'bike_church_patron_waiver') {

    $webform_submission = $vars['webform_submission'];

    $address = $webform_submission->getElementData('name_and_address_');

    $name = $address['given_name'] . ' ' . $address['family_name'];

    $markup = t('Thank you, the form was submitted for ') . $name;

    $vars['message']['#markup'] = $markup;
  }
  elseif ($vars['webform']->id() == 'nbw_youth_application_waiver'){
    $webform_submission = $vars['webform_submission'];
    $address = $webform_submission->getElementData('youth_address');
    $name = $address['given_name'] . ' ' . $address['family_name'];
    $markup = t('Thank you, the Waiver was recorded for ') . $name;
    $vars['message']['#markup'] = $markup;
  }
}

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 *
 * @return void
 */
function nbw_data_app_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id): void {
  //dpm('from my module: ' . $form_id);
  //\Drupal::messenger()->addMessage(t("form id is - " . $form_id));
    if ($form_id == 'user_form') {
      //dpm($form['actions']);
/*      \Drupal::messenger()->addMessage(t("We're about to edit this user!!"));*/

      $user = $form_state->getFormObject()->getEntity();

      $nbw_youth_profile = \Drupal::entityTypeManager()
        ->getStorage('profile')
        ->loadByProperties([
          'uid' => $user->id(),
          'type' => 'nbw_youth_profile',
        ]);
      //dpr($nbw_youth_profile);
      //$form['actions']['submit']['#value'] = t("Save this awesome article!");

    } elseif ($form_id == 'webform_submission_check_in_students_to_mon_wed_sum_add_form') {
      \Drupal::messenger()->addMessage(t("form id is - " . $form_id));
      //dpr($form_state);
    }
}

/**
 * Implements hook_entity_id_insert().

 * @param \Drupal\Core\Entity\EntityInterface $entity

 *
 * @return void
 */
//nbw_data_app_entity_insert
function nbw_data_app_webform_submission_insert(\Drupal\Core\Entity\EntityInterface $entity) {
  //dpr($entity);
  \Drupal::messenger()->addMessage(t("webform id is: " . $entity->getWebform()->id()));
  if ($entity->getWebform()->id() == 'record_volunteer_time' ){
    $webfor_data = $entity->getData();
    $hours = $webfor_data['number_of_hours'];
    $volunteer = $webfor_data['volunteer_'];
    $nbw_record_profiles = \Drupal::entityTypeManager()
      ->getStorage('profile')
      ->loadByProperties([
        'uid' => $volunteer,
        'type' => 'nbw_volunteer_profile',
      ]);
    if(!empty($nbw_record_profiles)) {
      foreach ($nbw_record_profiles as $profile) {
        //dpm($profile->get('field_miles_total')->value);
        $hours_total_new = floatval($profile->get('field_hours_total')->value) + $hours;
        $profile->get('field_hours_total')->setValue($hours_total_new);
        $profile->save();
      }
    } else {
      $nbw_volunteer_profile = Profile::create([
        'type' => 'nbw_volunteer_profile',
        'uid' => $volunteer,
        'field_hours_total' => $hours,
      ]);
      $nbw_volunteer_profile->save();
    }

  }

/*  $miles = $entity->get('miles_ridden')->getValue();
  $hours = $entity->get('hours')->getValue();

  $riders = $entity->get('riders')->getValue();

  \Drupal::messenger()->addMessage(t("hours: " . $hours . " miles: " . $miles));*/
  //dpm($miles);
/*  $attendees = $form_state->getValue('field_youth_attended');
  //dpm($attendees);

  foreach($attendees as $youth) {

    // Get NBW profiles by the YouthID
    $nbw_record_profiles = \Drupal::entityTypeManager()
      ->getStorage('profile')
      ->loadByProperties([
        'uid' => $youth,
        'type' => 'nbw_record',
      ]);

    foreach($nbw_record_profiles as $profile) {
      //dpm($profile->get('field_miles_total')->value);
      $miles_total_new = floatval($profile->get('field_miles_total')->value) + $miles;
      $hours_total_new = floatval($profile->get('field_hours_total')->value) + $hours;
      $profile->get('field_miles_total')->setValue($miles_total_new);
      $profile->get('field_hours_total')->setValue($hours_total_new);
      $profile->save();
    }

  }*/
  //$entity->webform_id
}

/**
 * Implements hook_element_info_alter().
 */
function nbw_data_app_element_info_alter(array &$types) {
  // Attach our extra CSS for toolbar icons.
  if (isset($types['toolbar'])) {
    $types['toolbar']['#attached']['library'][] = 'nbw_data_app/toolbar';
  }
}

/*function nbw_data_app_views_pre_execute(&$view) {
  dpq($view->build_info['query']);
}*/
//webform_submission
